apiVersion: v1alpha1
kind: Installation
metadata:
  name: robotworld-signoz
spec:
  deployment:
    flavor: compose
    mode: docker
  signoz:
    spec:
      image: signoz/signoz:v0.137.1
  ingester:
    spec:
      image: signoz/signoz-otel-collector@sha256:6d1a59bc553e041014597eff0970608948c5c7447aaa984c4d109f2bc9f4062c
